# Support the author by using the funding links below.
# Developed and maintained by Ciro Mota with the help of awesome contributors.
# Buy Me a Coffee: https://buymeacoffee.com/warengonzaga

ko_fi: ciromota

# Sponsoring this project means a lot to me, this will help me to continue building great open-source projects just like this.
# Wanna get in touch? Check out my bio links: https://links.ciromota.tec.br/
